### ISSUE TITLE
 Add automatic creation of a virtual microphone

### ISSUE THREAD

**Issue by kirilwapj** [lHumaNl/EchoWarp#25]
I'm trying to use this program to drop a microphone into a virtual machine. Since there are no microphones connected to it, it is necessary to use a virtual one.
The virtual microphone device created through the VBCable program, unfortunately, could not be made to work through your software. 

Please provide recommendations through which driver to create a virtual microphone if a real one is not connected. 

Or even better if there is an opportunity to add automatic creation of a virtual microphone to the software.

**Comment by lHumaNl** [comment]
@kirilwapj Hello! At the moment, the utility is not fully functional because it has bugs related to audio encoding/decoding and a few other minor issues. I don't have the time to address them right now due to my main job. As for your question, implementing such a feature in Python is not feasible because it does not provide access to the OS kernel. Additionally, creating any device requires developing a driver for a specific OS, which is beyond the scope of my project. As an alternative, you could continue using VBCable or install Steam (which automatically creates a virtual microphone).
